#!/usr/bin/env bash
#
#Wrapper for python script to get env variables to persist.
#Author: Adrian Larkeryd, 2016
#In order to load all modules
#source module_load_sbcs_latest

`/data/SBCS-Informatics/utilities/helper_script_moduleloadlatest.py` 2> /dev/null

